from os.path import join

# PATH TO THE FULL DATASET
FULL_DATASET_PATH : str = "./full_dataset"

# PATH TO THE XML FILE CONTAINING ALL THE LABELS
LABELS_XML_FILEPATH : str = join(FULL_DATASET_PATH, "labels.xml")

# PATH TO THE NEW DATASET
DATASET_PATH : str = "./dataset"

# NUMBER OF IMAGES TO USE IN THE NEW CLEAN DATASET
NB_IMAGES : int = 2200

# NUMBER OF TRAINING IMAGES
NB_TRAIN_IMAGES : int = 2000

# NUMBER OF TESTING IMAGES
NB_TEST_IMAGES : int = 200

# THE PATH TO THE XML FILE CONTAINING THE TRAIN LABELS
TRAIN_XML_FILEPATH : str = join(DATASET_PATH, "train.xml")

# THE PATH TO THE XML FILE CONTAINING THE TEST IMAGES
TEST_XML_FILEPATH : str = join(DATASET_PATH, "test.xml")

# WHERE TO SAVE THE MODEL ?
OUTPUT_MODEL_PATH: str = "./output_model.dat"